// code to run on server at startup
Meteor.startup(function () {
	// Challenges.remove({});
	

	Games.remove({});

	if (Challenges.find({}).count() === 0) {
		var challengeSeeds = [
			"Dr. Seuss - Love & Weirdness\nWe are all a little weird and life's a little weird, and when we find someone whose weirdness is compatible with ours, we join up with them and fall in mutual weirdness and call it love.",
			"Francis Bacon - Integrity\nIt's not what we eat but what we digest that makes us strong; not what we gain but what we save that makes us rich; not what we read but what we remember that makes us learned; and not what we profess but what we practice that gives us integrity.",
			"Abraham Lincoln - Katherine\nI am not bound to win, but I am bound to be true. I am not bound to succeed, but I am bound to live by the light that I have. I must stand with anybody that stands right, and stand with him while he is right, and part with him when he goes wrong.",
			"Albert Einstein\nI am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
			"Lemony Snicket - Trust\nDeciding whether or not to trust a person is like deciding whether or not to climb a tree because you might get a wonderful view from the highest branch or you might simply get covered in sap and for this reason many people choose to spend their time alone and indoors where it is harder to get a splinter.",
			"J. K. Rowling\nIt is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all -- in which case, you fail by default.",
			"Confucius\nTo put the world in order, we must first put the nation in order; to put the nation in order, we must put the family in order; to put the family in order, we must cultivate our personal life; and to cultivate our personal life, we must first set our hearts right.",
			"JK Rowling - Harry Potter and the Order of the Phoenix\nNow I want you to listen to me closely. You’re not a bad person. You’re a very good person, who bad things have happened to. Do you understand? Besides, the world isn’t split into good people and Death Eaters. We have all got both light and dark inside us. What matters is the power we choose to act on. That’s who we really are.",
			"Albert Einstein - Learning\nBear in mind that the wonderful things you learn in your schools are the work of many generations. All this is put in your hands as your inheritance in order that you may receive it, honor it, add to it, and one day faithfully hand it on to your children.",
			"Homer - The Odyssey\nMay the gods grant you all things which your heart desires, and may they give you a husband and a home and gracious concord, for there is nothing greater and better than this - when a husband and wife keep a household in oneness of mind, a great woe to their enemies and joy to their friends, and win high renown.",
			"Socrates - Fear of Death\nTo fear death, my friends, is only to think ourselves wise, without being wise: for it is to think that we know what we do not know. For anything that men can tell, death may be the greatest good that can happen to them: but they fear it as if they knew quite well that it was the greatest of evils. And what is this but that shameful ignorance of thinking that we know what we do not know?",
			"Dr. David M. Bums - Perfectionism\nAim for success, not perfection. Never give up your right to be wrong, because then you will lose the ability to learn new things and move forward with your life. Remember that fear always lurks behind perfectionism. Confronting your fears and allowing yourself the right to be human can, paradoxically, make yourself a happier and more productive person.",
			"Albert Einstein\nThe most beautiful thing we can experience is the mysterious. It is the source of all true art and all science. He to whom this emotion is a stranger, who can no longer pause to wonder and stand rapt in awe, is as good as dead: his eyes are closed.",
			"Martin Luther King Jr. - With this faith\nWith this faith, we will be able to hew out of the mountain of despair a stone of hope. With this faith, we will be able to transform the jangling discords of our nation into a beautiful symphony of brotherhood. With this faith, we will be able to work together, to pray together, to struggle together, to go to jail together, to stand up for freedom together, knowing that we will be free one day.",
			"The Hitchhiker's Guide to the Galaxy\nThis planet has - or rather had - a problem, which was this: most of the people living on it were unhappy for pretty much all of the time. Many solutions were suggested for this problem, but most of these were largely concerned with the movement of small green pieces of paper, which was odd because on the whole it wasn't the small green pieces of paper that were unhappy.",
			"The Hitchhiker's Guide to the Galaxy\nThe Hitchhiker’s Guide to the Galaxy has a few things to say on the subject of towels. A towel, it says, is about the most massively useful thing an interstellar hitch hiker can have. Partly it has great practical value - you can wrap it around you for warmth as you bound across the cold moons of Jaglan Beta; you can lie on it on the brilliant marble‐sanded beaches of Santraginus V, inhaling the heady sea vapours; you can sleep under it beneath the stars which shine so redly on the desert world of Kakrafoon; use it to sail a mini raft down the slow heavy river Moth; wet it for use in hand‐to‐hand‐combat; wrap it round your head to ward off noxious fumes or to avoid the gaze of the Ravenous Bugblatter Beast of Traal (a mindbogglingly stupid animal, it assumes that if you can't see it, it can't see you - daft as a bush, but very ravenous); you can wave your towel in emergencies as a distress signal, and of course dry yourself off with it if it still seems to be clean enough.",
			"The Hitchhiker's Guide to the Galaxy\nPeople of Earth, your attention, please. This is Prostetnic Vogon Jeltz of the Galactic Hyperspace Planning Council. As you will no doubt be aware, the plans for development of the outlying regions of the Galaxy require the building of a hyperspatial express route through your star system. And regrettably, your planet is one of those scheduled for demolition. The process will take slightly less than two of your Earth minutes. Thank you.\nThere’s no point in acting surprised about it. All the planning charts and demolition orders have been on display at your local planning department in Alpha Centauri for 50 of your Earth years, so you’ve had plenty of time to lodge any formal complaint and it’s far too late to start making a fuss about it now. … What do you mean you’ve never been to Alpha Centauri? Oh, for heaven’s sake, mankind, it’s only four light years away, you know. I’m sorry, but if you can’t be bothered to take an interest in local affairs, that’s your own lookout. Energize the demolition beams.",
			"The Hitchhiker's Guide to the Galaxy\nFor instance, on the planet Earth, man had always assumed that he was more intelligent than dolphins because he had achieved so much - the wheel, New York, wars and so on - whilst all the dolphins had ever done was muck about in the water having a good time. But conversely, the dolphins had always believed that they were far more intelligent than man - for precisely the same reasons.\nThe last ever dolphin message was misinterpreted as a surprisingly sophisticated attempt to do a double-backwards-somersault through a hoop whilst whistling the 'Star Spangled Banner', but in fact the message was this: So long and thanks for all the fish.",
			"The Hitchhiker's Guide to the Galaxy\nAnother thing that got forgotten was the fact that against all probability a sperm whale had suddenly been called into existence several miles above the surface of an alien planet.\nAnd since this is not a naturally tenable position for a whale, this poor innocent creature had very little time to come to terms with its identity as a whale before it then had to come to terms with not being a whale any more.",
			"Star Wars - A New Hope - Opening Crawl\nA long time ago, in a galaxy far, far away.... It is a period of civil war. Rebel spaceships, striking from a hidden base, have won their first victory against the evil Galactic Empire. During the battle, rebel spies managed to steal secret plans to the Empire's ultimate weapon, the DEATH STAR, an armored space station with enough power to destroy an entire planet. Pursued by the Empire's sinister agents, Princess Leia races home aboard her starship, custodian of the stolen plans that can save her people and restore freedom to the galaxy....",
			"Pulp Fiction - \"Ezekiel 25:17\"\nWell there's this passage I got memorized. Ezekiel 25:17. 'The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness. For he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know I am the Lord when I lay my vengeance upon thee.",
			"Fight Club - \"The rules...\"\nWelcome to Fight Club. The first rule of Fight Club is: you do not talk about Fight Club. The second rule of Fight Club is: you DO NOT talk about Fight Club! Third rule of Fight Club: if someone yells 'stop!', goes limp, or taps out, the fight is over. Fourth rule: only two guys to a fight. Fifth rule: one fight at a time, fellas. Sixth rule: no shirts, no shoes. Seventh rule: fights will go on as long as they have to. And the eighth and final rule: if this is your first night at Fight Club, you have to fight.",
			"American History X - \"Hate is baggage\"\nSo I guess this is where I tell you what I learned – my conclusion, right? Well, my conclusion is: Hate is baggage. Life's too short to be pissed off all the time. It's just not worth it. Derek says it's always good to end a paper with a quote. He says someone else has already said it best. So if you can't top it, steal from them and go out strong. So I picked a guy I thought you'd like.'We are not enemies, but friends. We must not be enemies. Though passion may have strained, it must not break our bonds of affection. The mystic chords of memory will swell when again touched, as surely they will be, by the better angels of our nature.'",
			"A Bronx Tale - \"Wasted Talent...\"\nSonny and my father always said that when I get older I would understand. Well, I finally did. I learned something from these two men. I learned to give love and get love unconditionally. You just have to accept people for what they are, and I learned the greatest gift of all. The saddest thing in life is wasted talent, and the choices that you make will shape your life forever. But you can ask anybody from my neighborhood, and they’ll just tell you this is just another Bronx tale.",
			"A Few Good Men\nYou can't handle the truth! Son, we live in a world that has walls, and those walls have to be guarded by men with guns. Who's gonna do it? You? You, Lieutenant Weinberg? I have a greater responsibility than you can possibly fathom. You weep for Santiago, and you curse the Marines. You have that luxury. You have the luxury of not knowing what I know -- that Santiago's death, while tragic, probably saved lives; and my existence, while grotesque and incomprehensible to you, saves lives. You don't want the truth because deep down in places you don't talk about at parties, you want me on that wall -- you need me on that wall. We use words like \"honor,\" \"code,\" \"loyalty.\" We use these words as the backbone of a life spent defending something. You use them as a punch line. I have neither the time nor the inclination to explain myself to a man who rises and sleeps under the blanket of the very freedom that I provide and then questions the manner in which I provide it. I would rather that you just said \"thank you\" and went on your way. Otherwise, I suggest you pick up a weapon and stand the post. Either way, I don't give a DAMN what you think you're entitled to!",
			"Air Force One\nI came here tonight to be congratulated. But today when I visited the Red Cross camps, overwhelmed by the flood of refugees fleeing from the horror of Kazakhstan, I realized I don't deserve to be congratulated. None of us do. Let's speak the truth. And the truth is, we acted too late. Only when our own national security was threatened did we act.\nRadek's regime murdered over 200,000 men, women and children and we watched it on TV. We let it happen. People were being slaughtered for over a year and we issued economical sanctions and hid behind a rhetoric of diplomacy. How dare we? The dead remember. Real peace is not just the absence of conflict, it's the presence of justice.\nAnd tonight, I come to you with a pledge to change America's policy. Never again will I allow our political self-interests to deter us from doing what we know to be morally right. Atrocity and terror are not political weapons and to those who would use them: Your day is over.\nWe will never negotiate.\nWe will no longer tolerate and we will no longer be afraid.\nIt's your turn to be afraid.",
			"Gladiator\nMy name is Maximus Decimus Meridius, commander of the Armies of the North, General of the Felix Legions and loyal servant to the TRUE emperor, Marcus Aurelius. Father to a murdered son, husband to a murdered wife. And I will have my vengeance, in this life or the next.",
			"Independence Day\nGood morning. In less than an hour, aircraft from here will join others from around the world. And you will be launching the largest aerial battle in this history of mankind. Mankind -- that word should have new meaning for all of us today. We can't be consumed by our petty differences anymore. We will be united in our common interests. Perhaps its fate that today is the 4th of July, and you will once again be fighting for our freedom, not from tyranny, oppression, or persecution -- but from annihilation. We're fighting for our right to live, to exist. And should we win the day, the 4th of July will no longer be known as an American holiday, but as the day when the world declared in one voice: \"We will not go quietly into the night! We will not vanish without a fight! We're going to live on! We're going to survive!\" Today, we celebrate our Independence Day!",
			"Jerry Maguire\nWell, don't worry. Don't worry.  I'm not gonna do what you all think I'm gonna do, which is just FLIP OUT! But let me just, let me just say, as I ease out of the office I helped build -- I'm sorry, but it's a FACT! -- that there is such a thing as manners, a way of treating people. These fish have manners. These fish have manners. In fact, they're coming with me. I'm starting a new company,and the fish will come with me. You can call me sentimental. The fish -- they're coming with me. Okay. If anybody else wants to come with me, this moment will be the moment of something real, and FUN, and inspiring in this god-forsaken business, and we will do it together. Who's comin' with me? Who's coming with me? Who's coming with me besides \"Flipper,\" here?",
			"Miracle\nGreat moments are born from great opportunity. And that's what you have here tonight, boys. That's what you've earned here, tonight. One game. If we played 'em ten times, they might win nine. But not this game. Not tonight. Tonight, we skate with 'em. Tonight, we stay with 'em, and we shut them down because we can! Tonight, we are the greatest hockey team in the world. You were born to be hockey players -- every one of ya. And you were meant to be here tonight. This is your time. Their time -- is done. It's over. I'm sick and tired of hearin' about what a great hockey team the Soviets have. Screw 'em! This is your time!! Now go out there and take it!",
			"The Shawshank Redemption\nRehabilitated? Well, now, let me see. You know, I don't have any idea what that means. I know what you think it means, sonny. To me, it's just a made up word, a politician's word, so that young fellas like yourself can wear a suit and a tie and have a job. What do you really wanna know? Am I sorry for what I did? There's not a day goes by I don't feel regret. Not because I'm in here, or because you think I should. I look back on the way I was then, a young, stupid kid who committed that terrible crime. I wanna talk to him. I wanna try to talk some sense to him -- tell him the way things are. But I can't. That kid's long gone and this old man is all that's left. I gotta live with that. Rehabilitated? It's just a bullshit word. So you go on and stamp your form, sonny, and stop wasting my time. Because to tell you the truth, I don't give a shit."
		];

		// Manually set ID numbers for all documents in this mongo collection.
		// This is to allow us to randomly pull one out later.
		var id = 0;

		_.each(challengeSeeds, function(seed) {
			Challenges.insert({
				_id: (id++).toString(),
				text: seed
			});
		});
	}
});
